In [1]:
import pandas as pd

GroupBy in Pandas

In [3]:
data ={
    "Name": ["Aman","Saurav","Karan","Shubham","Abhishek",None,"Sameer"],
    "Age": [22,23,None,22,25,24,26],
    "Marks": [85,None, 88,90,56,72,None],
    "Subject": ["Math","Physics","Math","Chemistry","Math","Physics","Chemistry"]
}
df = pd.DataFrame(data)
print(df)

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
1    Saurav  23.0    NaN    Physics
2     Karan   NaN   88.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math
5       NaN  24.0   72.0    Physics
6    Sameer  26.0    NaN  Chemistry

In [ ]:
df.groupby('Subject')['Marks'].mean() #mean marks per subject

Subject
Chemistry    90.000000
Math         76.333333
Physics      72.000000
Name: Marks, dtype: float64

In [ ]:
df.groupby('Subject')['Name'].count() #count students per subject

Subject
Chemistry    2
Math         3
Physics      1
Name: Name, dtype: int64

In [6]:
# multiple aggregations
df.groupby('Subject')['Marks'].agg(['mean','max','min'])

                mean   max   min
Subject
Chemistry  90.000000  90.0  90.0
Math       76.333333  88.0  56.0
Physics    72.000000  72.0  72.0

In [7]:
# multiple aggregations
df.groupby('Subject')['Marks'].agg(['mean','max','min','count'])

                mean   max   min  count
Subject
Chemistry  90.000000  90.0  90.0      1
Math       76.333333  88.0  56.0      3
Physics    72.000000  72.0  72.0      1

In [ ]:
# froup by multiple 
df.groupby(['Subject','Age'])['Marks'].mean()

Subject    Age
Chemistry  22.0    90.0
           26.0     NaN
Math       22.0    85.0
           25.0    56.0
Physics    23.0     NaN
           24.0    72.0
Name: Marks, dtype: float64