The Raw Data

Reference Table: This is the raw data provided by the admin.
| Name     | Age     | Marks   | Subject   |
| -------- | ------- | ------- | --------- |
| Aman     | 22      | 85      | Math      |
| Saurav   | 23      | Missing | Physics   |
| Karan    | Missing | 88      | Math      |
| Shubham  | 22      | 90      | Chemistry |
| Abhishek | 25      | 56      | Math      |
| Missing  | 24      | 72      | Physics   |
| Sameer   | 26      | Missing | Chemistry |

Note: “Missing” indicates data was not captured (NaN/None).

In [ ]:
import pandas as pd

Task 1.1: Create the DataFrame
Construct a Pandas DataFrame named df that replicates the "Raw Data" table shown in the previous slide. Use None or np.nan for missing values.
Generate a statistical summary (mean/min/max) for the numerical columns.

In [2]:
df = pd.DataFrame({
    "Name": ["Aman","Saurav","Karan","Shubham","Abhishek",None,"Sameer"],
    "Age": [22,23,None,22,25,24,26],
    "Marks": [85,None, 88,90,56,72,None],
    "Subject": ["Math","Physics","Math","Chemistry","Math","Physics","Chemistry"]
})
df

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
1    Saurav  23.0    NaN    Physics
2     Karan   NaN   88.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math
5       NaN  24.0   72.0    Physics
6    Sameer  26.0    NaN  Chemistry

Task 1.2: Basic Inspection
Once created:

Check the shape of the dataset.

Display the data types of the columns.

In [3]:
type(df)

pandas.DataFrame

In [4]:
df.describe()

             Age      Marks
count   6.000000   5.000000
mean   23.666667  78.200000
std     1.632993  14.254824
min    22.000000  56.000000
25%    22.250000  72.000000
50%    23.500000  85.000000
75%    24.750000  88.000000
max    26.000000  90.000000

Exercise 2: Selection & Aggregation

Task: Filter and group the data.


Selection: Create a view showing only the 'Name' and 'Marks' columns.

In [5]:
df[["Name","Marks"]]

       Name  Marks
0      Aman   85.0
1    Saurav    NaN
2     Karan   88.0
3   Shubham   90.0
4  Abhishek   56.0
5       NaN   72.0
6    Sameer    NaN


Filtering: Select students who have scored more than 80 marks.

In [6]:
df[df["Marks"]>80]

      Name   Age  Marks    Subject
0     Aman  22.0   85.0       Math
2    Karan   NaN   88.0       Math
3  Shubham  22.0   90.0  Chemistry


Complex Filtering: Select students older than 22 who also scored more than 80.

In [7]:
df[(df["Age"]>22)&(df["Marks"]>80)]

Empty DataFrame
Columns: [Name, Age, Marks, Subject]
Index: []


Aggregation: Count how many students are enrolled in each Subject.

In [8]:
df["Subject"].value_counts

<bound method IndexOpsMixin.value_counts of 0         Math
1      Physics
2         Math
3    Chemistry
4         Math
5      Physics
6    Chemistry
Name: Subject, dtype: str>

Exercise 3: Sorting & Ranking

Task: Order the data to find rankers.


Sort the dataframe by 'Marks' in descending order.

In [9]:
df.sort_values("Marks",ascending=False)

       Name   Age  Marks    Subject
3   Shubham  22.0   90.0  Chemistry
2     Karan   NaN   88.0       Math
0      Aman  22.0   85.0       Math
5       NaN  24.0   72.0    Physics
4  Abhishek  25.0   56.0       Math
1    Saurav  23.0    NaN    Physics
6    Sameer  26.0    NaN  Chemistry


Use a specific Pandas function to find the top 2 highest scorers (Scholarship Candidates) without sorting the whole dataframe manually.

In [10]:
df.nlargest(2,"Marks")

      Name   Age  Marks    Subject
3  Shubham  22.0   90.0  Chemistry
2    Karan   NaN   88.0       Math


Identify the student with the lowest marks (Remedial Candidate).

In [11]:
df.nsmallest(1,"Marks")

       Name   Age  Marks Subject
4  Abhishek  25.0   56.0    Math

Exercise 4: Data Cleaning

Task: Handle Missing Values.

Calculate the total number of missing values (NaN) in each column.

In [12]:
df.isnull().sum()

Name       1
Age        1
Marks      2
Subject    0
dtype: int64


Filter and display the rows where 'Marks' are missing.

In [13]:
df[df["Marks"].isnull()]

     Name   Age  Marks    Subject
1  Saurav  23.0    NaN    Physics
6  Sameer  26.0    NaN  Chemistry


Create a new dataframe called cleaned_df by removing any row that contains even a single missing value.

In [14]:
cleaned_df = df.dropna()
print(cleaned_df)

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math


Compare the shape of cleaned_df vs original df.

In [15]:
print("Original df shape:", df.shape)
print("Cleaned df:", cleaned_df.shape)

Original df shape: (7, 4)
Cleaned df: (3, 4)

1.Look at the 'Marks' column in your output. Why are the values floats instead of integers?

Because the column contains missing values (NaN). In Pandas, NaN is a floating-point value, so the entire column is automatically converted to float datatype to accommodate NaN.

2.What is the risk of using implace = True when dropping missing values?

It permanently modifies the original dataframe.

You cannot easily recover the original data if needed later.

Makes debugging harder since no copy is preserved.

3. Based on the data, what specific feedback should u give to the admin regarding the "Name" column?


The Name column contains missing entries, which indicates incomplete data entry. Names should be mandatory or validated during data collection to avoid unidentified student records and maintain data integrity.