In [2]:
import pandas as pd

In [3]:
data = {
    "Name": ["John","Karan","Ben","Oscar","Richard","Olivia","Jeffery","Oswald","Rohn","Robin"],
     "Department": ["IT", "Sales", "Sales","Sales","IT","HR", "IT", "Sales","IT", "IT"],
     "Roles": ["Developer","Analyst","Analyst","Analyst", "Developer", "Manager", "Developer", "Analyst","Developer","Developer"],
     "Experience": [3, 5, 4, 4, 8, 12, 6, 4, 2, 5],
     "Salary": [10000, 30000, 50000, 30000, 25000, 29000, 40000, 22000, 110000, 30000],
     "Score": [4.5, 3.2, 4.8, 3.9, None, 4.9, 3.4, 4.5, 3.9, None ]
}
df= pd.DataFrame(data)
print(df)

      Name Department      Roles  Experience  Salary  Score
0     John         IT  Developer           3   10000    4.5
1    Karan      Sales    Analyst           5   30000    3.2
2      Ben      Sales    Analyst           4   50000    4.8
3    Oscar      Sales    Analyst           4   30000    3.9
4  Richard         IT  Developer           8   25000    NaN
5   Olivia         HR    Manager          12   29000    4.9
6  Jeffery         IT  Developer           6   40000    3.4
7   Oswald      Sales    Analyst           4   22000    4.5
8     Rohn         IT  Developer           2  110000    3.9
9    Robin         IT  Developer           5   30000    NaN

In [4]:
df.groupby('Department')['Salary'].mean()

Department
HR       29000.0
IT       43000.0
Sales    33000.0
Name: Salary, dtype: float64

In [5]:
# df.groupby('ROle')['Score'].mean()

In [6]:
df.isnull()

    Name  Department  Roles  Experience  Salary  Score
0  False       False  False       False   False  False
1  False       False  False       False   False  False
2  False       False  False       False   False  False
3  False       False  False       False   False  False
4  False       False  False       False   False   True
5  False       False  False       False   False  False
6  False       False  False       False   False  False
7  False       False  False       False   False  False
8  False       False  False       False   False  False
9  False       False  False       False   False   True

In [7]:
df.groupby('Department')['Salary'].agg(['mean','max','min','count'])

               mean     max    min  count
Department
HR          29000.0   29000  29000      1
IT          43000.0  110000  10000      5
Sales       33000.0   50000  22000      4

In [8]:
# multiple aggregations
# df.groupby('Role')['Score'].agg(['mean','max','min','count'])

In [9]:
# df.groupby(['Department','Role'])['Salary'].mean()